spring.application.name=ecomarket-backend
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecomarket_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgre}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secreto=${JWT_SECRETO:CAMBIAR_SECRETO}
jwt.expiracion-minutos=${JWT_EXPIRACION_MINUTOS:120}

admin.correo=${ADMIN_CORREO:admin@ecomarket.pe}
admin.contrasena=${ADMIN_CONTRASENA:CAMBIAR_PASSWORD}

cors.origenes=${CORS_ORIGENES:http://localhost:4200}

geocodificacion.habilitada=${GEOCODIFICACION_HABILITADA:true}
geocodificacion.url=${GEOCODIFICACION_URL:https://nominatim.openstreetmap.org}
geocodificacion.agente=${GEOCODIFICACION_AGENTE:EcoMarket-UPC/1.0 (proyecto academico)}

gemini.api-key=${GEMINI_API_KEY:}
gemini.modelo=${GEMINI_MODELO:gemini-2.5-flash}
gemini.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta}
gemini.tiempo-espera-segundos=${GEMINI_TIEMPO_ESPERA:10}